apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: propertylogger
  name: propertylogger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: propertylogger
  strategy: {}
  template:
    metadata:
      labels:
        app: propertylogger
    spec:
      containers:
        - image: propertylogger:local
          # imagePullPolicy is important to use imported local image. Always would pull from dockerhub or similar registry
          imagePullPolicy: IfNotPresent
          name: propertylogger
          resources: {}
          env:
            # - name: SPRING_CONFIG_ADDITIONALLOCATION
            #   value: /app/secrets/

            # ## spring cloud
            # - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLED
            #   value: "false"
            # - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLED
            #   value: "true"
            # - name: MANAGEMENT_HEALTH_KUBERNETES_ENABLED
            #   value: "false"
            # - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
            #   value: /app/secrets/

            ## spring.import.config
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configtree:/app/secrets/*/"
          volumeMounts:
            - name: secret-properties
              mountPath: /app/secrets/firstsecret/
            - name: secret-properties-2
              mountPath: /app/secrets/secondsecret/
      volumes:
        - name: secret-properties
          secret:
            secretName: secret-properties
        - name: secret-properties-2
          secret:
            secretName: secret-properties-2
