apiVersion: v1
kind: Secret
metadata:
  name: secret-properties
stringData:
  frist_secret_key: frist_secret_value
  second_secret_key: second_secret_value
  secret_key.with.points: test
  third: third
  password.super: secret###########
